### ISSUE TITLE
when running  test_electricity_system.m, G.graph_state() have not defined

### ISSUE THREAD

**Issue by Tehnrry** [carlobar/PDToolbox_matlab#2]
when running  test_electricity_system.m, G.graph_state() have not defined, How to solve?
In additional, I use the graph_final_state.m to conpute, but the 5 agents have the same states, not like the Figure 16: Final demand profile of each agent in documentation of Population Dynamics Toolbox.pdf.

**Comment by carlobar** [comment]
Hi, instead of 'G.graph_state()', please use 'G.state(t)', which returns the state of the system at time t. You can see the last state with 'G.state(end)'.

In the example all the agents had the same valuation, that's why their demand and utility is identical. I just added few lines to define different valuations (the loop in the line 29 of 'test_electricity_system.m' defines the valuation of agents).
