### ISSUE TITLE
Define new dynamics

### ISSUE THREAD

**Issue by niccoloraspa** [carlobar/PDToolbox_matlab#3]
Hello,
thanks for the Toolbox it looks great. Could you elaborate more on how is it possible to define new dynamics? I've read the documentation but it's not mentioned at all. Thanks

**Comment by carlobar** [comment]
Hi, 

Thanks for pointing out this issue. The toolbox calls the functions from the folder 'dynamics' to update the strategy of each population. The inputs of the function are 1) simulation time and 2) a vector with the population's state. The output is a vector that indicates the state's direction of change.

All the dynamics use the same code to do some basic operations. For example, the following commands transform the input vector into a matrix of size P x n:


global G norm_dx

% extract matrix of strategies
n = max(G.S);
x_n = vec2mat(z,n);
x = zeros(G.P, n);

for p = 1 : G.P
    x(p, :) = x_n(p, :) * G.m(p);
end


Since the system's state is a normalized vector, we need to multiply the strategies by the mass of the population. The last loop do this.

The variable 'norm_dx' stores the norm of the output vector, which is used to determine whether the system converged. Convergence occurs when the strategies remain constant. In this case, the system converges when the output vector has a small magnitude. The code at the end of the dynamics calculate this norm:


dz = [x_dot_v];
if G.stop_c == true
    norm_dx = norm(dz);
end


The ODE solver uses the file 'dynamics/stopevent.m', which evaluates norm_dx, to determine when to stop the simulation.

Hope this helps, 

Carlos

**Comment by niccoloraspa** [comment]
Thank you.
